# Generated by Django 5.2.5 on 2025-09-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
