# Generated by Django 5.2.5 on 2025-09-11 18:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_vaccinecampaign_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='campaign_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='vaxCamp_tqt2sl', max_length=255),
        ),
    ]
