# Generated by Django 5.2.5 on 2025-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_vaccinecampaign_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
