# Generated by Django 5.2.5 on 2025-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_vaccinecampaign_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinecampaign',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
