# Generated by Django 5.2.5 on 2025-08-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.vaccinecampaign'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='first_dose_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_dose_bookings', to='campaigns.vaccineschedule'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='second_dose_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_dose_bookings', to='campaigns.vaccineschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignreview',
            unique_together={('patient', 'campaign')},
        ),
    ]
