# Generated by Django 5.2.5 on 2025-08-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_campaignreview_patient_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.patientprofile'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to='users.patientprofile'),
        ),
    ]
