# Generated by Django 5.2.5 on 2025-09-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_payment_campaign_id_payment_schedule_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_reference',
        ),
    ]
