# Generated by Django 5.2.5 on 2025-09-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_payment_payment_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignreview',
            unique_together=set(),
        ),
    ]
